CREATE TABLE IF NOT EXISTS runtime_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO runtime_config (key, value) VALUES
('strategies', '[
    {"name":"Aggressive","min_edge":0.05,"min_confidence":0.40,"kelly_fraction":0.50,"max_signals_per_day":10,"min_bet":5.0},
    {"name":"Balanced","min_edge":0.06,"min_confidence":0.40,"kelly_fraction":0.25,"max_signals_per_day":5,"min_bet":5.0},
    {"name":"Conservative","min_edge":0.08,"min_confidence":0.50,"kelly_fraction":0.15,"max_signals_per_day":3,"min_bet":15.0}
]'::jsonb),
('global', '{
    "scan_interval_mins": 30,
    "news_scan_interval_mins": 10,
    "bet_scan_interval_mins": 10,
    "heartbeat_interval_mins": 60,
    "retrain_interval_hours": 24,
    "model_sidecar_url": "",
    "llm_model": "gpt-4o",
    "llm_models": ["openai/gpt-oss-120b:free","nvidia/nemotron-3-super-120b-a12b:free","google/gemma-4-31b-it:free","openai/gpt-oss-20b:free"],
    "news_enabled": false,
    "slippage_pct": 0.01,
    "fee_pct_default": 0.0,
    "fee_pct_crypto": 0.018,
    "fee_pct_sports": 0.0075,
    "fee_pct_politics": 0.01,
    "fee_pct_finance": 0.01,
    "fee_pct_other": 0.0125,
    "min_volume": 1000.0,
    "min_book_depth": 200.0,
    "kelly_fraction": 0.25,
    "max_days_to_expiry": 14,
    "max_llm_candidates": 1,
    "max_model_candidates": 15,
    "min_effective_edge": 0.08,
    "consensus_agents": 2,
    "calibration_min_samples": 20,
    "max_markets_fetch": 1000,
    "min_price": 0.03,
    "max_price": 0.97,
    "strategy_bankroll": 300.0,
    "active_strategies": ["aggressive","balanced","conservative"],
    "stop_loss_pct": 999.0,
    "exit_days_before_expiry": 0,
    "block_sports": true,
    "block_yes_side": true,
    "lr_damping": 0.5,
    "min_kelly_size": 0.02,
    "min_bet_price": 0.15,
    "http_timeout_secs": 30,
    "news_fetch_timeout_secs": 15,
    "sidecar_timeout_secs": 10,
    "sidecar_retries": 3,
    "sidecar_retry_delay_secs": 2,
    "alert_throttle_mins": 15,
    "ws_bet_cooldown_secs": 600,
    "price_alert_cooldown_secs": 3600,
    "max_ws_bets_per_day": 3,
    "ws_reconnect_delay_secs": 5,
    "ws_min_price_delta": 0.03,
    "ws_min_trade_usd": 500.0,
    "metrics_port": 9000
}'::jsonb)
ON CONFLICT (key) DO NOTHING;
